apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: {{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}
          ports:
            - containerPort: {{ .Values.order.port }}
