apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: {{ .Values.product.image.repository }}:{{ .Values.product.image.tag }}
          ports:
            - containerPort: {{ .Values.product.service.port }}
